"""add holdings ledger and executions tables

Revision ID: 0e2ec47780fd
Revises: 5932ac4e0183
Create Date: 2026-05-25 07:24:41.712886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e2ec47780fd'
down_revision: Union[str, Sequence[str], None] = '5932ac4e0183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_orders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('time_in_force', sa.Enum('DAY', 'GTC', 'IOC', name='timeinforce'), nullable=False),
    sa.Column('client_order_id', sa.String(length=50), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_trade_orders_broker_order_id'), 'trade_orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_trade_orders_symbol'), 'trade_orders', ['symbol'], unique=False)
    op.create_index('ix_trade_orders_user_id_status', 'trade_orders', ['user_id', 'status'], unique=False)
    op.create_table('user_balances',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('locked_cash', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_balances_user_id'), 'user_balances', ['user_id'], unique=False)
    op.create_table('cash_ledger',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'ORDER_LOCK', 'ORDER_UNLOCK', 'ORDER_SETTLE', name='ledgertype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['trade_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_ledger_user_id'), 'cash_ledger', ['user_id'], unique=False)
    op.create_table('order_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['trade_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_executions_order_id'), 'order_executions', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_executions_symbol'), 'order_executions', ['symbol'], unique=False)
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_symbol'), table_name='transactions')
    op.drop_table('transactions')
    op.add_column('holdings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('holdings', sa.Column('average_cost', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('holdings', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_holdings_portfolio_id'), table_name='holdings')
    op.drop_constraint(op.f('uq_holdings_portfolio_symbol'), 'holdings', type_='unique')
    op.create_index('ix_holdings_user_id', 'holdings', ['user_id'], unique=False)
    op.create_unique_constraint('uq_holdings_user_symbol', 'holdings', ['user_id', 'symbol'])
    op.drop_constraint(op.f('holdings_portfolio_id_fkey'), 'holdings', type_='foreignkey')
    op.create_foreign_key(None, 'holdings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('holdings', 'avg_cost')
    op.drop_column('holdings', 'portfolio_id')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='user_role_enum'),
               type_=sa.Enum('user', 'admin', name='role'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::user_role_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'admin', name='role'),
               type_=postgresql.ENUM('user', 'admin', name='user_role_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::user_role_enum"))
    op.drop_column('users', 'deleted_at')
    op.add_column('holdings', sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('holdings', sa.Column('avg_cost', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.create_foreign_key(op.f('holdings_portfolio_id_fkey'), 'holdings', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_holdings_user_symbol', 'holdings', type_='unique')
    op.drop_index('ix_holdings_user_id', table_name='holdings')
    op.create_unique_constraint(op.f('uq_holdings_portfolio_symbol'), 'holdings', ['portfolio_id', 'symbol'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_holdings_portfolio_id'), 'holdings', ['portfolio_id'], unique=False)
    op.alter_column('holdings', 'symbol',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('holdings', 'average_cost')
    op.drop_column('holdings', 'user_id')
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('side', postgresql.ENUM('BUY', 'SELL', name='order_side_enum'), autoincrement=False, nullable=False),
    sa.Column('order_type', postgresql.ENUM('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='order_type_enum'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('FILLED', 'PENDING', 'CANCELLED', name='order_status_enum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('transactions_portfolio_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('ix_transactions_symbol'), 'transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('cash_balance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('portfolios_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolios_pkey'))
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.drop_index(op.f('ix_order_executions_symbol'), table_name='order_executions')
    op.drop_index(op.f('ix_order_executions_order_id'), table_name='order_executions')
    op.drop_table('order_executions')
    op.drop_index(op.f('ix_cash_ledger_user_id'), table_name='cash_ledger')
    op.drop_table('cash_ledger')
    op.drop_index(op.f('ix_user_balances_user_id'), table_name='user_balances')
    op.drop_table('user_balances')
    op.drop_index('ix_trade_orders_user_id_status', table_name='trade_orders')
    op.drop_index(op.f('ix_trade_orders_symbol'), table_name='trade_orders')
    op.drop_index(op.f('ix_trade_orders_broker_order_id'), table_name='trade_orders')
    op.drop_table('trade_orders')
    # ### end Alembic commands ###
